name: Build and Package Extensions

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build-and-package:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chrome]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build extension
        run: bun run build:${{ matrix.browser }}

      - name: Package extension
        run: |
          mkdir -p artifacts
          cd dist
          # Copy the appropriate manifest for each browser
          cp ../manifests/manifest.${{ matrix.browser }}.json ./manifest.json
          zip -r ../artifacts/${{ matrix.browser }}-extension.zip .
          cd ..
          ls -la artifacts/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.browser }}-extension
          path: artifacts/${{ matrix.browser }}-extension.zip
          retention-days: 5
          if-no-files-found: error
          compression-level: 6
          overwrite: true
